/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicAuthAccountRouteImport } from './routes/api/public/auth/account'
import { Route as ApiPublicFeedbackExportRouteImport } from './routes/api/public/feedback/export'
import { Route as ApiPublicMessagesSendRouteImport } from './routes/api/public/messages/send'
import { Route as ApiPublicNotifyRunRouteImport } from './routes/api/public/notify/run'
import { Route as ApiPublicNotifyTestRouteImport } from './routes/api/public/notify/test'
import { Route as ApiPublicNotifyUnsubscribeRouteImport } from './routes/api/public/notify/unsubscribe'
import { Route as ApiPublicPushSendRemindersRouteImport } from './routes/api/public/push/send-reminders'
import { Route as ApiPublicPushSubscribeRouteImport } from './routes/api/public/push/subscribe'
import { Route as ApiPublicPushTestRouteImport } from './routes/api/public/push/test'
import { Route as ApiPublicPushUnsubscribeRouteImport } from './routes/api/public/push/unsubscribe'
import { Route as ApiPublicAuthLinkedinCallbackRouteImport } from './routes/api/public/auth/linkedin/callback'
import { Route as ApiPublicAuthLinkedinStartRouteImport } from './routes/api/public/auth/linkedin/start'
import { Route as ApiPublicAuthLinkedinStatusRouteImport } from './routes/api/public/auth/linkedin/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthAccountRoute = ApiPublicAuthAccountRouteImport.update({
  id: '/api/public/auth/account',
  path: '/api/public/auth/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackExportRoute = ApiPublicFeedbackExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiPublicFeedbackRoute,
} as any)
const ApiPublicMessagesSendRoute = ApiPublicMessagesSendRouteImport.update({
  id: '/api/public/messages/send',
  path: '/api/public/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyRunRoute = ApiPublicNotifyRunRouteImport.update({
  id: '/api/public/notify/run',
  path: '/api/public/notify/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyTestRoute = ApiPublicNotifyTestRouteImport.update({
  id: '/api/public/notify/test',
  path: '/api/public/notify/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyUnsubscribeRoute =
  ApiPublicNotifyUnsubscribeRouteImport.update({
    id: '/api/public/notify/unsubscribe',
    path: '/api/public/notify/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushSendRemindersRoute =
  ApiPublicPushSendRemindersRouteImport.update({
    id: '/api/public/push/send-reminders',
    path: '/api/public/push/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushSubscribeRoute = ApiPublicPushSubscribeRouteImport.update({
  id: '/api/public/push/subscribe',
  path: '/api/public/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushTestRoute = ApiPublicPushTestRouteImport.update({
  id: '/api/public/push/test',
  path: '/api/public/push/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushUnsubscribeRoute =
  ApiPublicPushUnsubscribeRouteImport.update({
    id: '/api/public/push/unsubscribe',
    path: '/api/public/push/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthLinkedinCallbackRoute =
  ApiPublicAuthLinkedinCallbackRouteImport.update({
    id: '/api/public/auth/linkedin/callback',
    path: '/api/public/auth/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthLinkedinStartRoute =
  ApiPublicAuthLinkedinStartRouteImport.update({
    id: '/api/public/auth/linkedin/start',
    path: '/api/public/auth/linkedin/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthLinkedinStatusRoute =
  ApiPublicAuthLinkedinStatusRouteImport.update({
    id: '/api/public/auth/linkedin/status',
    path: '/api/public/auth/linkedin/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRouteWithChildren
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/auth/account': typeof ApiPublicAuthAccountRoute
  '/api/public/feedback/export': typeof ApiPublicFeedbackExportRoute
  '/api/public/messages/send': typeof ApiPublicMessagesSendRoute
  '/api/public/notify/run': typeof ApiPublicNotifyRunRoute
  '/api/public/notify/test': typeof ApiPublicNotifyTestRoute
  '/api/public/notify/unsubscribe': typeof ApiPublicNotifyUnsubscribeRoute
  '/api/public/push/send-reminders': typeof ApiPublicPushSendRemindersRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/test': typeof ApiPublicPushTestRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/auth/linkedin/callback': typeof ApiPublicAuthLinkedinCallbackRoute
  '/api/public/auth/linkedin/start': typeof ApiPublicAuthLinkedinStartRoute
  '/api/public/auth/linkedin/status': typeof ApiPublicAuthLinkedinStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRouteWithChildren
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/auth/account': typeof ApiPublicAuthAccountRoute
  '/api/public/feedback/export': typeof ApiPublicFeedbackExportRoute
  '/api/public/messages/send': typeof ApiPublicMessagesSendRoute
  '/api/public/notify/run': typeof ApiPublicNotifyRunRoute
  '/api/public/notify/test': typeof ApiPublicNotifyTestRoute
  '/api/public/notify/unsubscribe': typeof ApiPublicNotifyUnsubscribeRoute
  '/api/public/push/send-reminders': typeof ApiPublicPushSendRemindersRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/test': typeof ApiPublicPushTestRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/auth/linkedin/callback': typeof ApiPublicAuthLinkedinCallbackRoute
  '/api/public/auth/linkedin/start': typeof ApiPublicAuthLinkedinStartRoute
  '/api/public/auth/linkedin/status': typeof ApiPublicAuthLinkedinStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRouteWithChildren
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/auth/account': typeof ApiPublicAuthAccountRoute
  '/api/public/feedback/export': typeof ApiPublicFeedbackExportRoute
  '/api/public/messages/send': typeof ApiPublicMessagesSendRoute
  '/api/public/notify/run': typeof ApiPublicNotifyRunRoute
  '/api/public/notify/test': typeof ApiPublicNotifyTestRoute
  '/api/public/notify/unsubscribe': typeof ApiPublicNotifyUnsubscribeRoute
  '/api/public/push/send-reminders': typeof ApiPublicPushSendRemindersRoute
  '/api/public/push/subscribe': typeof ApiPublicPushSubscribeRoute
  '/api/public/push/test': typeof ApiPublicPushTestRoute
  '/api/public/push/unsubscribe': typeof ApiPublicPushUnsubscribeRoute
  '/api/public/auth/linkedin/callback': typeof ApiPublicAuthLinkedinCallbackRoute
  '/api/public/auth/linkedin/start': typeof ApiPublicAuthLinkedinStartRoute
  '/api/public/auth/linkedin/status': typeof ApiPublicAuthLinkedinStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/feedback'
    | '/api/public/version'
    | '/api/public/auth/account'
    | '/api/public/feedback/export'
    | '/api/public/messages/send'
    | '/api/public/notify/run'
    | '/api/public/notify/test'
    | '/api/public/notify/unsubscribe'
    | '/api/public/push/send-reminders'
    | '/api/public/push/subscribe'
    | '/api/public/push/test'
    | '/api/public/push/unsubscribe'
    | '/api/public/auth/linkedin/callback'
    | '/api/public/auth/linkedin/start'
    | '/api/public/auth/linkedin/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/feedback'
    | '/api/public/version'
    | '/api/public/auth/account'
    | '/api/public/feedback/export'
    | '/api/public/messages/send'
    | '/api/public/notify/run'
    | '/api/public/notify/test'
    | '/api/public/notify/unsubscribe'
    | '/api/public/push/send-reminders'
    | '/api/public/push/subscribe'
    | '/api/public/push/test'
    | '/api/public/push/unsubscribe'
    | '/api/public/auth/linkedin/callback'
    | '/api/public/auth/linkedin/start'
    | '/api/public/auth/linkedin/status'
  id:
    | '__root__'
    | '/'
    | '/api/public/feedback'
    | '/api/public/version'
    | '/api/public/auth/account'
    | '/api/public/feedback/export'
    | '/api/public/messages/send'
    | '/api/public/notify/run'
    | '/api/public/notify/test'
    | '/api/public/notify/unsubscribe'
    | '/api/public/push/send-reminders'
    | '/api/public/push/subscribe'
    | '/api/public/push/test'
    | '/api/public/push/unsubscribe'
    | '/api/public/auth/linkedin/callback'
    | '/api/public/auth/linkedin/start'
    | '/api/public/auth/linkedin/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRouteWithChildren
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicAuthAccountRoute: typeof ApiPublicAuthAccountRoute
  ApiPublicMessagesSendRoute: typeof ApiPublicMessagesSendRoute
  ApiPublicNotifyRunRoute: typeof ApiPublicNotifyRunRoute
  ApiPublicNotifyTestRoute: typeof ApiPublicNotifyTestRoute
  ApiPublicNotifyUnsubscribeRoute: typeof ApiPublicNotifyUnsubscribeRoute
  ApiPublicPushSendRemindersRoute: typeof ApiPublicPushSendRemindersRoute
  ApiPublicPushSubscribeRoute: typeof ApiPublicPushSubscribeRoute
  ApiPublicPushTestRoute: typeof ApiPublicPushTestRoute
  ApiPublicPushUnsubscribeRoute: typeof ApiPublicPushUnsubscribeRoute
  ApiPublicAuthLinkedinCallbackRoute: typeof ApiPublicAuthLinkedinCallbackRoute
  ApiPublicAuthLinkedinStartRoute: typeof ApiPublicAuthLinkedinStartRoute
  ApiPublicAuthLinkedinStatusRoute: typeof ApiPublicAuthLinkedinStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/account': {
      id: '/api/public/auth/account'
      path: '/api/public/auth/account'
      fullPath: '/api/public/auth/account'
      preLoaderRoute: typeof ApiPublicAuthAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback/export': {
      id: '/api/public/feedback/export'
      path: '/export'
      fullPath: '/api/public/feedback/export'
      preLoaderRoute: typeof ApiPublicFeedbackExportRouteImport
      parentRoute: typeof ApiPublicFeedbackRoute
    }
    '/api/public/messages/send': {
      id: '/api/public/messages/send'
      path: '/api/public/messages/send'
      fullPath: '/api/public/messages/send'
      preLoaderRoute: typeof ApiPublicMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/run': {
      id: '/api/public/notify/run'
      path: '/api/public/notify/run'
      fullPath: '/api/public/notify/run'
      preLoaderRoute: typeof ApiPublicNotifyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/test': {
      id: '/api/public/notify/test'
      path: '/api/public/notify/test'
      fullPath: '/api/public/notify/test'
      preLoaderRoute: typeof ApiPublicNotifyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/unsubscribe': {
      id: '/api/public/notify/unsubscribe'
      path: '/api/public/notify/unsubscribe'
      fullPath: '/api/public/notify/unsubscribe'
      preLoaderRoute: typeof ApiPublicNotifyUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/send-reminders': {
      id: '/api/public/push/send-reminders'
      path: '/api/public/push/send-reminders'
      fullPath: '/api/public/push/send-reminders'
      preLoaderRoute: typeof ApiPublicPushSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/subscribe': {
      id: '/api/public/push/subscribe'
      path: '/api/public/push/subscribe'
      fullPath: '/api/public/push/subscribe'
      preLoaderRoute: typeof ApiPublicPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/test': {
      id: '/api/public/push/test'
      path: '/api/public/push/test'
      fullPath: '/api/public/push/test'
      preLoaderRoute: typeof ApiPublicPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/unsubscribe': {
      id: '/api/public/push/unsubscribe'
      path: '/api/public/push/unsubscribe'
      fullPath: '/api/public/push/unsubscribe'
      preLoaderRoute: typeof ApiPublicPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/linkedin/callback': {
      id: '/api/public/auth/linkedin/callback'
      path: '/api/public/auth/linkedin/callback'
      fullPath: '/api/public/auth/linkedin/callback'
      preLoaderRoute: typeof ApiPublicAuthLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/linkedin/start': {
      id: '/api/public/auth/linkedin/start'
      path: '/api/public/auth/linkedin/start'
      fullPath: '/api/public/auth/linkedin/start'
      preLoaderRoute: typeof ApiPublicAuthLinkedinStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/linkedin/status': {
      id: '/api/public/auth/linkedin/status'
      path: '/api/public/auth/linkedin/status'
      fullPath: '/api/public/auth/linkedin/status'
      preLoaderRoute: typeof ApiPublicAuthLinkedinStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicFeedbackRouteChildren {
  ApiPublicFeedbackExportRoute: typeof ApiPublicFeedbackExportRoute
}

const ApiPublicFeedbackRouteChildren: ApiPublicFeedbackRouteChildren = {
  ApiPublicFeedbackExportRoute: ApiPublicFeedbackExportRoute,
}

const ApiPublicFeedbackRouteWithChildren =
  ApiPublicFeedbackRoute._addFileChildren(ApiPublicFeedbackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRouteWithChildren,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicAuthAccountRoute: ApiPublicAuthAccountRoute,
  ApiPublicMessagesSendRoute: ApiPublicMessagesSendRoute,
  ApiPublicNotifyRunRoute: ApiPublicNotifyRunRoute,
  ApiPublicNotifyTestRoute: ApiPublicNotifyTestRoute,
  ApiPublicNotifyUnsubscribeRoute: ApiPublicNotifyUnsubscribeRoute,
  ApiPublicPushSendRemindersRoute: ApiPublicPushSendRemindersRoute,
  ApiPublicPushSubscribeRoute: ApiPublicPushSubscribeRoute,
  ApiPublicPushTestRoute: ApiPublicPushTestRoute,
  ApiPublicPushUnsubscribeRoute: ApiPublicPushUnsubscribeRoute,
  ApiPublicAuthLinkedinCallbackRoute: ApiPublicAuthLinkedinCallbackRoute,
  ApiPublicAuthLinkedinStartRoute: ApiPublicAuthLinkedinStartRoute,
  ApiPublicAuthLinkedinStatusRoute: ApiPublicAuthLinkedinStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
